name: packing
on: [push]

jobs:
  
  pack_linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: build
        shell: bash
        run: |
          cd solver_application/
          cmake -B build
          cmake --build build
        
      - name: pack TGZ
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G TGZ
          cd ../..
          mv solver_application/build/*.tar.gz artifacts
          
      - name: pack ZIP
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G ZIP          
          cd ../..
          mv solver_application/build/*.zip artifacts
          
      - name: pack DEB
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G DEB
          cd ../..
          mv solver_application/build/*.deb artifacts
          
      - name: pack RPM
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G RPM
          cd ../..
          mv solver_application/build/*.rpm artifacts
          
      - name: push on
        shell: bash
        run: |
          git config --global user.name "xypimr"
          git config --global user.email "kiselev.nik.v@gmail.com"
          cd artifacts/
          git add *.deb *.rpm
          git commit -m "added deb & rpm"
          git push --force origin HEAD:master
          
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release
        
  pack_macos:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        shell: bash
        run: |
          cd solver_application/
          cmake -B build
          cmake --build build

      - name: pack DMG
        shell: bash
        run: |
          cd solver_application/build/
          cpack -G DragNDrop
          cd ../..
          mv solver_application/build/*.dmg artifacts
          
      - name: push on
        shell: bash
        run: |
          git config --global user.name "xypimr"
          git config --global user.email "kiselev.nik.v@gmail.com"
          git pull origin HEAD:master
          cd artifacts/
          git add *dmg
          git commit -m "added dmg"
          git push --force origin HEAD:master
          
  pack_windows:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: build
        run: |
          cd solver_application/
          cmake -B build
          cmake --build build
          
      - name: pack MSI
        run: |
          cd solver_application/build/
          cpack -G WIX
          cd ../..
          mv solver_application/build/*.msi artifacts
          
      - name: push on
        run: |
          git config --global user.name "xypimr"
          git config --global user.email "kiselev.nik.v@gmail.com"
          git pull origin HEAD:master
          cd artifacts/
          git add *msi
          git commit -m "added msi"
          git push --force origin HEAD:master
